# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 07:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=25)),
                ('priority', models.CharField(max_length=1)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Company_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=25)),
                ('salutation', models.CharField(max_length=3)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('e_mail', models.EmailField(max_length=254)),
                ('board_number', models.CharField(max_length=12)),
                ('mobile_number', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('is_correct_contact', models.BooleanField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Executive_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=20)),
                ('executive_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database_app.Executive_User')),
            ],
        ),
        migrations.CreateModel(
            name='Junior_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('logs', models.TextField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_app.Company_Details')),
            ],
        ),
        migrations.CreateModel(
            name='Member_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Senior_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database_app.Executive_User')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database_app.Member_User')),
            ],
        ),
        migrations.AddField(
            model_name='junior_user',
            name='senior_mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database_app.Senior_User'),
        ),
        migrations.AddField(
            model_name='junior_user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database_app.Member_User'),
        ),
        migrations.AddField(
            model_name='executive_user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database_app.Member_User'),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database_app.Industry'),
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database_app.Member_User'),
        ),
        migrations.AddField(
            model_name='brand',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_app.Company'),
        ),
    ]
