# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0002_auto_20151231_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'permissions': (('view', 'Can see contents of the model'),)},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': (('view', 'Can see contents of the model'),)},
        ),
        migrations.AlterModelOptions(
            name='company_details',
            options={'permissions': (('view', 'Can see contents of the model'),)},
        ),
        migrations.AlterModelOptions(
            name='executive_user',
            options={'permissions': (('view', 'Can see contents of the model'),)},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'permissions': (('view', 'Can see contents of the model'),)},
        ),
        migrations.AlterModelOptions(
            name='junior_user',
            options={'permissions': (('view', 'Can see contents of the model'),)},
        ),
        migrations.AlterModelOptions(
            name='logs',
            options={'permissions': (('view', 'Can see contents of the model'),)},
        ),
        migrations.AlterModelOptions(
            name='senior_user',
            options={'permissions': (('view', 'Can see contents of the model'),)},
        ),
    ]
