# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0003_auto_20151231_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'permissions': (('view', 'Can see contents of Brand'),)},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': (('view', 'Can see contents of Company'),)},
        ),
        migrations.AlterModelOptions(
            name='company_details',
            options={'permissions': (('view', 'Can see contents of Company_Details'),)},
        ),
        migrations.AlterModelOptions(
            name='executive_user',
            options={'permissions': (('view', 'Can see contents of Executive_User'),)},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'permissions': (('view', 'Can see contents of Industry'),)},
        ),
        migrations.AlterModelOptions(
            name='junior_user',
            options={'permissions': (('view', 'Can see contents of Junior_User'),)},
        ),
        migrations.AlterModelOptions(
            name='logs',
            options={'permissions': (('view', 'Can see contents of Logs'),)},
        ),
        migrations.AlterModelOptions(
            name='senior_user',
            options={'permissions': (('view', 'Can see contents of Senior_User'),)},
        ),
    ]
