# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 15:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0004_auto_20151231_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 2, 15, 7, 0, 966615, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 2, 15, 7, 19, 161403, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company_details',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 2, 15, 7, 33, 331116, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company_details',
            name='designation',
            field=models.CharField(default='HR Manager', max_length=25),
            preserve_default=False,
        ),
    ]
